# Generated by Django 4.2.11 on 2024-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('date_sortie', models.DateField()),
                ('realisateur', models.CharField(max_length=250)),
                ('act_prin', models.CharField(max_length=250)),
                ('avis', models.TextField()),
                ('pub', models.BooleanField(default=False)),
                ('note', models.IntegerField(default=0)),
            ],
        ),
    ]
