# Generated by Django 5.0.4 on 2024-04-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesFiches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviecard',
            name='act_prin',
        ),
        migrations.AddField(
            model_name='moviecard',
            name='acteur',
            field=models.ManyToManyField(related_name='films', to='lesFiches.acteur'),
        ),
        migrations.AlterField(
            model_name='moviecard',
            name='realisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='lesFiches.realisateur'),
        ),
    ]
